---
- hosts: all
  become: yes
  roles:
    - role: common
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

- hosts: dhcp
  become: yes
  roles:
    - role: dhcp

- hosts: dns
  become: yes
  roles:
    - role: dns
