---
- name: "download networkboot/dhcpd docker image"
  docker_image:
    name: "networkboot/dhcpd"
    state: present

- name: "create dhcp data directory"
  file:
    name: "{{ data_dir }}"
    state: "directory"

- name: "store dhcpd.conf file"
  template:
    src: "dhcpd.conf.j2"
    dest: "{{ data_dir }}/dhcpd.conf"
