---
- name: "download plgr/bind image"
  docker_image:
    name: "plgr/bind"
    state: present

- name: "create dns data directory"
  file:
    name: "{{ data_dir }}"
    state: directory

- name: "stores local named configuration file"
  template:
    src: "named.conf.local.j2"
    dest: "{{ data_dir }}/named.conf.local"

- name: "stores zone db file"
  template:
    src: "db.zone.j2"
    dest: "{{ data_dir }}/db.{{ zone_name }}"

- name: "stores reverse zone db file"
  template:
    src: "db.reverse_zone.j2"
    dest: "{{ data_dir }}/db.{{ reverse_zone_name }}"

- name: "store ddns key file"
  template:
    src: "ddns.key.j2"
    dest: "{{ data_dir }}/ddns.key"

- name: "run dns docker container"
  docker_container:
    name: "dns"
    detach: yes
    volumes: "{{ data_dir }}:/data"
    exposed_ports:
      - "53/udp"
      - "53/tcp"
    ports:
      - "{{ ansible_eth0['ipv4']['address'] }}:53:53/udp"
      - "{{ ansible_eth0['ipv4']['address'] }}:53:53/tcp"
    image: "plgr/bind"
    restart_policy: "always"
    state: started
    restart: yes
