---
- name: "download plgr/bind image"
  docker_image:
    name: "plgr/bind"
    state: present

- name: "create dns data directory"
  file:
    name: "{{ data_dir }}"
    state: directory

- name: "stores local named configuration file"
  template:
    src: "named.conf.local.j2"
    dest: "{{ data_dir }}/named.conf.local"
